### ISSUE TITLE
训练效果不佳

### ISSUE THREAD

**Issue by pengwb9527** [yuanconghao/openai-finetuning#1]
用你的数据训练完，不管问什么，都是问答“亲爱的主人，要多注意身体啊。”
![1](https://github.com/yuanconghao/openai-finetuning/assets/70902702/6020bb05-aef0-46f1-b507-33a7ffcb01ed)

我自己准备的数据，训练完，更加差，答非所问。为什么呢？

**Comment by yuanconghao** [comment]
具体可以看下我的博客：https://deeplearner.top/2023/09/14/AIGC-%E5%A4%A7%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83-OpenAI-%E5%8C%BB%E5%AD%A6%E5%A4%A7%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83/
